#pragma once

namespace nichess {

const int NUM_ROWS = 8;
const int NUM_COLUMNS = 8;
const int NUM_SQUARES = NUM_ROWS * NUM_COLUMNS;
const int NUM_STARTING_PIECES = 16;
const int ACTION_SKIP = -1;

const int KING_STARTING_HEALTH_POINTS = 10;
const int MAGE_STARTING_HEALTH_POINTS = 10;
const int PAWN_STARTING_HEALTH_POINTS = 30;
const int WARRIOR_STARTING_HEALTH_POINTS = 60;
const int ASSASSIN_STARTING_HEALTH_POINTS = 10;
const int KNIGHT_STARTING_HEALTH_POINTS = 60;

const int KING_ABILITY_POINTS = 100;
const int MAGE_ABILITY_POINTS = 30;
const int PAWN_ABILITY_POINTS = 100;
const int WARRIOR_ABILITY_POINTS = 30;
const int ASSASSIN_ABILITY_POINTS = 30;
const int KNIGHT_ABILITY_POINTS = 100;

const int PAWN_THROW_DAMAGE = 100;
const int PAWN_THROW_DAMAGE_2 = 10;
const int KNIGHT_THROW_DAMAGE = 100;
const int KNIGHT_THROW_DAMAGE_2 = 10;
const int MAGE_THROW_DAMAGE_1 = 100;
const int MAGE_THROW_DAMAGE_2 = 20;
const int WARRIOR_THROW_DAMAGE_1 = 100;
const int WARRIOR_THROW_DAMAGE_2 = 20;
const int MAGE_ASSASSIN_DAMAGE = 30;

const int NUM_PLAYERS = 2;
const int NUM_PIECE_TYPE = 13;

enum Direction: int {
  NORTH = 0, NORTHEAST, EAST, SOUTHEAST,
  SOUTH, SOUTHWEST, WEST, NORTHWEST,
  INVALID
};
const int NUM_DIRECTIONS = 9;
const int NUM_DIRECTIONS_WITHOUT_INVALID = NUM_DIRECTIONS - 1;
const int NUM_DIAGONAL_DIRECTIONS = 4;
const Direction DIAGONAL_DIRECTIONS[] = {Direction::NORTHEAST, Direction::SOUTHEAST, Direction::SOUTHWEST, Direction::NORTHWEST};
const Direction NON_DIAGONAL_DIRECTIONS[] = {Direction::NORTH, Direction::EAST, Direction::SOUTH, Direction::WEST};

} // namespace nichess
